### ISSUE TITLE
Something wrong about the training process

### ISSUE THREAD

**Issue by CRLqinliang** [droid-dataset/droid_policy_learning#10]
Hi, when I used droid_100 datasets train the model, at the beginning, everything went well, until this error came out:

> “Traceback (most recent call last):
  File "/home/wrs/miniconda3/envs/droid_policy_learning/lib/python3.10/tkinter/__init__.py", line 4046, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7f062dea7a30>
Traceback (most recent call last):
  File "/home/wrs/miniconda3/envs/droid_policy_learning/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7f062dea7a30>

And the whole process was killed, so I went to search for the problem, and got this answer:

```
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
```

However, I found this code in the file **visualization.lib**, and still met this error during training.

**Comment by CRLqinliang** [comment]
@kpertsch  Thank you for your reply!
I tried to run the three lines in my Python shell, it went well.
![image](https://github.com/droid-dataset/droid_policy_learning/assets/111740705/4c5e51ba-c4b0-4a81-bd91-251f26527bfe)

When I rerun the training code, it stuck here this time:
![image](https://github.com/droid-dataset/droid_policy_learning/assets/111740705/7e461247-47ee-498a-8617-e82f480183a8)

It seems like randomly stuck, no matter whether doing the plot or not. (Confused)

**Comment by kpertsch** [comment]
Mmh that's odd -- could you try killing your program that's stuck with Ctrl+C to see where in the program it got stuck? Very hard to debug such silent freezing issues.

**Comment by CRLqinliang** [comment]
@kpertsch Okay, I tried to Ctrl+C to see what happened, and got this:
![image](https://github.com/droid-dataset/droid_policy_learning/assets/111740705/213c50ee-7b41-4d97-854b-0013e6d29d79)
The program is waiting for the unlock of the thread and is stuck here.

This is my OS(WSL2) configuration:
![image](https://github.com/droid-dataset/droid_policy_learning/assets/111740705/75d0c3b9-8efc-44d7-b6e4-3c599b6b5fe5)
GPUs configuration:
![image](https://github.com/droid-dataset/droid_policy_learning/assets/111740705/ebff0243-8263-449f-a08e-280447d14c29)

I change the parameters of training to those: 
` "traj_transform_threads": 48, "traj_read_threads": 48, "shuffle_buffer_size": 100000,`;
so I think the RAM is enough to run this code.

**Comment by kpertsch** [comment]
@ashwin-balakrishna96 have you seen such behavior before? 
It seems that the data parallel wrapper around the visual encoder locks up. Can you try running with only a single GPU visible via `export CUDA_VISIBLE_DEVICES=0`?

**Comment by CRLqinliang** [comment]
@kpertsch okay, I will try it and let you know the result.
Thank you so much.

**Comment by ldddddddl** [comment]
Hello, I try to train policy with droid_100, but I always get the following error:
——————
Did you mean: droid_100 -> coil100 ?

The builder directory D:\droid-main\dataset\droid_100\droid_100 doesn't contain any versions.
No builder could be found in the directory: D:\droid-main\dataset\droid_100 for the builder: droid_100.
——————————
My droid_runs_language_conditioned_rlds is set like this:
DATA_PATH = r"D:\droid-main\dataset\droid_100"    # UPDATE WITH PATH TO RLDS DATASETS
EXP_LOG_PATH = r"D:\droid-main\temp_log" # UPDATE WITH PATH TO DESIRED LOGGING DIRECTORY
EXP_NAMES = OrderedDict(
    [
        # Note: you can add co-training dataset here appending
        # a new dataset to "datasets" and adjusting "sample_weights"
        # accordingly
        ("droid_100", {"datasets": ["droid_100"],
                   "sample_weights": [1]})                                    
    ])
——————
Is there a problem with that? If you can, please share the following how you set it up?

**Comment by ashwin-balakrishna96** [comment]
That should work, perhaps something went wrong with preserving the correct directory structure when downloading the dataset? Can you confirm that the directory structure is as follows:

Within DATA_PATH there should be a folder called `droid_100`, and within that there should be a folder called `1.0.0`. Inside the `1.0.0` folder you'll find a number of json and tfrecord files.

**Comment by ldddddddl** [comment]
> That should work, perhaps something went wrong with preserving the correct directory structure when downloading the dataset? Can you confirm that the directory structure is as follows:
> 
> Within DATA_PATH there should be a folder called `droid_100`, and within that there should be a folder called `1.0.0`. Inside the `1.0.0` folder you'll find a number of json and tfrecord files.

Yes, it is work now, but it still comes up sometimes. it's so weird.

**Comment by himanibelsare** [comment]
Hi,

When I run: 

`python robomimic/scripts/config_gen/droid_runs_language_conditioned_rlds.py --wandb_proj_name <WANDB_PROJ_NAME>
`

I get the error:

```
/droid/droid_policy_learning/robomimic/scripts/train.py", line 120, in <listcomp>
    [make_dataset_from_rlds(**dataset_kwargs, train=True)[1] for dataset_kwargs in dataset_kwargs_list]
TypeError: make_dataset_from_rlds() got an unexpected keyword argument 'state_obs_keys'
```


my variables are set as:

DATA_PATH = "../../../dataset/1.0.0"    # UPDATE WITH PATH TO RLDS DATASETS
EXP_LOG_PATH = "../../../checkpoints/" # UPDATE WITH PATH TO DESIRED LOGGING DIRECTORY
EXP_NAMES = OrderedDict(
    [
        # Note: you can add co-training dataset here appending
        # a new dataset to "datasets" and adjusting "sample_weights"
        # accordingly
        ("droid", {"datasets": ["droid"],
                   "sample_weights": [1]})                                    
    ])
